Add category selection if a human player is active
BelfDev/uofg-msc-team-project pull request #28
Opened 2020-02-03 19:47 UTC by Arden488

Based on user story: https://trello.com/c/CsqdWW6l

This PR:
- adds category selection logic (from a human player point of view)
- adds some styling
- updates some previous related pieces

2020-02-03 19:56 UTC, hughwin approved these changes

2020-02-04 11:44 UTC, nathanieldschneider approved these changes
Please can you commit more frequently - your commits should tell a story of the changes you have made throughout a PR so we get a clear idea of what you have done. Otherwise, it looks good. ;)

2020-02-04 11:48 UTC, BelfDev requested changes
The PR looks good! I'd just ask to keep with the "Attribute" semantics instead of "Category".

2020-02-04 11:48 UTC, BelfDev commented on src/main/resources/com/toptrumps/online/scripts/card.js
> +                category: $target.data("category")
Can we keep the "Attribute" semantics?

2020-02-04 11:48 UTC, BelfDev commented on src/main/resources/com/toptrumps/online/scripts/game.js
> +    const NUMBER_OF_AI_PLAYERS = 4;
This is temporary, right?

2020-02-04 12:50 UTC, Arden488 commented on src/main/resources/com/toptrumps/online/scripts/card.js
> +                category: $target.data("category")
Updated throughout the code

2020-02-04 12:50 UTC, Arden488 commented on src/main/resources/com/toptrumps/online/scripts/game.js
> +    const NUMBER_OF_AI_PLAYERS = 4;
Yes
I added TODO comment

2020-02-04 12:51 UTC, BelfDev approved these changes

2020-02-04 12:51 UTC, merged