Feature/round results
BelfDev/uofg-msc-team-project pull request #35
Opened 2020-02-04 20:42 UTC by rjs68

-Added toString method in RoundOutcome that displays the result of the round
-Changed the onRoundEnd method to take advantage of the new toString method
-Created additional onRoundEnd methods to account for and display and players that have been eliminated from the game

2020-02-04 21:07 UTC, hughwin commented
Added a commit on top to satisfy the story: "As a human player, when it is not my turn I want to be able to select next so that I can see the results of each round (2pts)".

2020-02-05 10:59 UTC, BelfDev requested changes
# Summary

- Please eliminate different ```onRoundEnd``` signatures
- Please revise the ```eliminatedPlayers``` logic
- Please double-check if we already have methods implemented (no need to use ```instanceof AIPlayer```
- Please remove ```onAiRoundWin()``` and use ```onRoundEnd```
- Please keep the presentation logic in the Controller/View

2020-02-05 10:59 UTC, BelfDev commented on src/main/java/com/toptrumps/core/engine/Game.java
> +        createAIPlayers(numberOfPlayers);
Oooops, sorry about that!

2020-02-05 10:59 UTC, BelfDev commented on src/main/java/com/toptrumps/core/engine/Game.java
> +            Player previousActivePlayer = null;
Do we really need this?

2020-02-05 10:59 UTC, BelfDev commented on src/main/java/com/toptrumps/core/engine/GameEventListener.java
> +    void onRoundEnd(final RoundOutcome outcome, final ArrayList<Player> eliminatedPlayers);
These are supposed to be life cycle methods. It's very confusing to have overloads in this case! We should keep online one "onRoundEnd" and pass to it everything we might need. If we have +3 parameters, then it's time to create an object.

2020-02-05 10:59 UTC, BelfDev commented on src/main/java/com/toptrumps/core/engine/GameEventListener.java
> +    void onAiRoundWin();
We certainly don't need this! ```onRoundEnd``` can return the correct winner (doesn't matter if it's AI or not).

2020-02-05 10:59 UTC, BelfDev commented on src/main/java/com/toptrumps/core/engine/Game.java
> +            if(previousActivePlayer instanceof AIPlayer){
We have a convenience method on ```Player``` to determine if it's AI or not.

2020-02-05 10:59 UTC, BelfDev commented on src/main/java/com/toptrumps/core/engine/Game.java
> +                        eliminatedPlayer = player;
We can get the eliminated player from just filtering players with empty decks. It's a minor tweak in the current logic, like this:

```
   ArrayList<Player> defeatedPlayers = (ArrayList<Player>) players.stream().filter(p -> p.getDeck().isEmpty()).collect(toList());
            players.removeAll(defeatedPlayers);
```

2020-02-05 10:59 UTC, BelfDev commented on src/main/java/com/toptrumps/core/engine/RoundOutcome.java
> +    public String toString(){
This is presentation logic. Should be done in the Controller.

2020-02-05 18:42 UTC, BelfDev requested changes
# Summary

Much better now!!!! Some great catches as well. 

- Please watch the semantics! 
- Please try to make what is going on inside the ```ìf```statements clearer.

2020-02-05 18:42 UTC, BelfDev commented on src/main/java/com/toptrumps/cli/CommandLineController.java
> +        String roundResult = "\nThe round resulted in a: ";
Above you have a ```RoundOutcome.Result``` object which you named ```result```. Just beneath you have a ```String``` named ```roundResult```. You see the issue here? Semantically, what's truly the result?

I think ```String roundResult``` is in fact your ```outcomeMessage```.

2020-02-05 18:42 UTC, BelfDev commented on src/main/java/com/toptrumps/cli/CommandLineController.java
> +                    if(player == outcome.getDraws().get(outcome.getDraws().size()-1)){
Look at this ```if``` statement. How can we make it clearer?

2020-02-05 18:42 UTC, BelfDev commented on src/main/java/com/toptrumps/cli/CommandLineController.java
> +    private void showEliminatedPlayers(ArrayList<Player> removedPlayers){
```showEliminatedPlayers``` received "removedPlayers" => Again, watch the semantics.

2020-02-05 18:42 UTC, BelfDev commented on src/main/java/com/toptrumps/core/engine/Game.java
> +            numberOfPlayers = players.size();
Sweeeeet!

2020-02-05 18:42 UTC, BelfDev commented on src/main/java/com/toptrumps/core/engine/RoundOutcome.java
> +    public enum Result {
I might refactor this later

2020-02-05 18:42 UTC, BelfDev commented on src/main/java/com/toptrumps/core/engine/RoundOutcome.java
> +    private RoundOutcome(Result result, Player winner, ArrayList<Player> draws, ArrayList<Player> removedPlayers) {
GREAT catch!!!! 10/10

2020-02-05 18:42 UTC, BelfDev commented on src/main/java/com/toptrumps/core/engine/RoundOutcome.java
> +    public ArrayList<Player> getRemovedPlayers(){
Removed or defeated? Let's choose something and stick to it.

2020-02-05 23:47 UTC, BelfDev approved these changes

2020-02-06 10:04 UTC, nathanieldschneider approved these changes

2020-02-06 10:13 UTC, Arden488 approved these changes

2020-02-06 10:34 UTC, merged