Update README.md
BelfDev/uofg-msc-team-project pull request #59
Opened 2020-02-09 11:59 UTC by hughwin

2020-02-09 12:20 UTC, BelfDev approved these changes
I'll double-check why the fourth step is necessary (copying TopTrumps.json). Perhaps we can incorporate it as part of the build process.

2020-02-10 09:12 UTC, BelfDev requested changes
@hughwin I found out what happened to you!

There's no need to copy the TopTrumps.json file into the same directory as the jar -- in fact, that's not ideal al all! All you need to do is to run the jar from your working directory, like this:

```java -jar target/TopTrumps.jar -o```

Can you please update the README?

 ps: The CommandLine mode is working at the moment because I haven't configured it to read from the .json config file yet.

2020-02-10 10:10 UTC, BelfDev approved these changes
Yayyy

2020-02-10 10:20 UTC, rjs68 approved these changes

2020-02-10 10:28 UTC, merged