Feature/game playability
BelfDev/uofg-msc-team-project pull request #62
Opened 2020-02-09 13:58 UTC by rjs68

-Made the cards slightly bigger to allow for the Witcher card names
-Ability to select ENTER to start the next round
-Added some scanner.nextLine() statements to clear the scanner to allow ENTER function to work

2020-02-09 14:12 UTC, hughwin approved these changes
LOL @ "Ability to select ENTER to start the next round" finally being put in - I've tried twice!

2020-02-10 09:32 UTC, BelfDev requested changes
Looking good! Just pointed out one minor detail about the relationship between ```view``` and ```controller```.

2020-02-10 09:32 UTC, BelfDev commented on src/main/java/com/toptrumps/cli/CommandLineView.java
> +    public void selectNextRound(Scanner scanner){
@rjs68 It's a good idea to keep things like "asking for input" in the ```Controller```. The view is only the UI component -- everything you need to print out on the screen. The ```Controller``` orchestrates the request for input, computation of game logic (model), and presentation of data (view).

2020-02-10 12:23 UTC, BelfDev approved these changes

2020-02-10 12:27 UTC, merged