Feature/print auto rounds
BelfDev/uofg-msc-team-project pull request #82
Opened 2020-02-12 21:38 UTC by rjs68

-Changed code so information is printed for all rounds - even when the human has been eliminated
-Separated out the printing of human info, such as number of cards and viewing their card, so that these only print if the human is alive
-Made use of IS_TEST_MODE attribute to speed up auto complete printing - I think we should rename this to something like AUTOCOMPLETE to be more intuitive!
-Changed print speeds to provide better user experience

2020-02-12 21:46 UTC, hughwin approved these changes

2020-02-12 22:04 UTC, BelfDev requested changes
IS_TEST_MODE is supposed to be a **constant** flag. If you really need a new flag, please rename it.

2020-02-12 22:04 UTC, BelfDev commented on src/main/java/com/toptrumps/cli/CommandLineController.java
> +        IS_TEST_MODE = false;
IS_TEST_MODE is a constant!

2020-02-13 14:01 UTC, rjs68 commented on src/main/java/com/toptrumps/cli/CommandLineController.java
> +        IS_TEST_MODE = false;
I've changed this now!

2020-02-13 15:01 UTC, BelfDev approved these changes
Awesome! 👍

2020-02-13 15:15 UTC, merged