Cleaned up retrieval of all previous game data.
BelfDev/uofg-msc-team-project pull request #88
Opened 2020-02-13 23:41 UTC by nathanieldschneider

Hey homies, 

Pull request has some merge errors that I will fix tomorrow.

Basically this PR just cleans up the process of pulling a list of all previous statistics. Now it pulls the player information from the database and writes that to a hashmap, and then uses that map to create the correct player objects. It also no longer passes a winnerID.

Also changed it so I'm getting resultset variables by column name and not index. Refactored the FullStats class a bit, Pedro needs to come up with a name because I'm too sleepy. 

**I will give away an award to whomever can fix my wee logic puzzle below.**

Basically, see this loop?

>      while(roundStats.next()){
                gameId = roundStats.getInt("game_id");
                if(gameId == allStats.get(counter).getGameID()){
                    allStats.get(counter).buildRoundStats(roundStats,players);
                    
                }else{
                        counter++;
                        if(gameId == allStats.get(counter).getGameID()){
                        allStats.get(counter).buildRoundStats(roundStats,players);
                }

What it does is it loops through the rows of a result set starting at the top and moving down. Through each row, it checks if the game ID of the row is the same as the counter, which is looping through all possible game IDs.

Why does it do this?

Well, because our player performance table can have multiple rows with the same game id, whereas the individual game data table has only one row per gameID. And we need to merge these two datasets into one object that has the right game id. So that's what the above code does.

**What's the problem?**

Can't you see? It's repetitive as fuck. This is because without checking a second time, the code will skip rows in the resultset- because it hit finds that the game ID doesn't much the current counter, so it increments the counter but it doesn't check again to see if it's the same as the next gameID. So the row just gets ignored and the loop moves on. _Yes I have tried using an OR statement to check for counter+1._

Anyway, Anton said make it better but I fucking can't reeeeeeeeeeee

2020-02-14 11:45 UTC, rjs68 requested changes

2020-02-14 11:45 UTC, rjs68 commented on src/main/java/com/toptrumps/db/Statistics.java
> +                        allStats.get(counter).buildRoundStats(roundStats,players);
I sent you a solution to this boiiii

2020-02-14 12:16 UTC, nathanieldschneider commented on src/main/java/com/toptrumps/db/Statistics.java
> +                        allStats.get(counter).buildRoundStats(roundStats,players);
implemented :) well done!

2020-02-14 12:26 UTC, rjs68 approved these changes

2020-02-14 15:48 UTC, Arden488 approved these changes
I'm going to approve. It's better than it was, but I would suggest reformating code, it's easy to do with IDE such as IntelliJ. Just add spaces and linebreaks

2020-02-14 15:48 UTC, Arden488 commented on src/main/java/com/toptrumps/db/FullStats.java
> +        this.winner = new Player(rs.getInt("winner_id"),players.get(rs.getInt("winner_id")));
Please-please-please, make three lines for this, instead of one. It's super unreadable

2020-02-14 15:49 UTC, Arden488 commented
And there are conflicts. Can you fix it by yourself or you need help?

2020-02-15 11:45 UTC, BelfDev approved these changes

2020-02-15 11:46 UTC, BelfDev commented
Please try to play a full game after you resolve the conflicts

2020-02-15 18:02 UTC, hughwin approved these changes

2020-02-15 19:55 UTC, merged